# Generated by Django 2.2.13 on 2021-12-29 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0005_auto_20190503_1657'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': '评论列表', 'verbose_name_plural': '评论列表'},
        ),
    ]
